version: '3.8'

services:
  app1:
    build: ./services/app1
    ports:
      - "8081:8081"

  app2:
    build: ./services/app2
    ports:
      - "8082:8082"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2