
services:
  app1:
    build: ./services/app1
    ports:
      - "8081:8081"

  app2:
    build: ./services/app2
    ports:
      - "8082:8082"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # Compact Thrift protocol (Agent)
      - "16686:16686" # UI
      - "14268:14268" # HTTP Thrift (Collector)
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"
      COLLECTOR_OTLP_ENABLED: "true"     